//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    
    
    /// <summary>
    /// The 'Baseword' entity class.
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/Models.EF")]
    public sealed partial class Baseword : Entity
    {
        
        private Nullable<int> _abbrevationId;
        
        private string _comment;
        
        private int _id;
        
        private Nullable<bool> _isLocked;
        
        private int _languageId;
        
        private long _referenceNumber;
        
        private Nullable<int> _status;
        
        private string _text;
        
        private Nullable<int> _value;
        
        private int _wordtypeId;
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();
        partial void OnAbbrevationIdChanging(Nullable<int> value);
        partial void OnAbbrevationIdChanged();
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnIsLockedChanging(Nullable<bool> value);
        partial void OnIsLockedChanged();
        partial void OnLanguageIdChanging(int value);
        partial void OnLanguageIdChanged();
        partial void OnReferenceNumberChanging(long value);
        partial void OnReferenceNumberChanged();
        partial void OnStatusChanging(Nullable<int> value);
        partial void OnStatusChanged();
        partial void OnTextChanging(string value);
        partial void OnTextChanged();
        partial void OnValueChanging(Nullable<int> value);
        partial void OnValueChanged();
        partial void OnWordtypeIdChanging(int value);
        partial void OnWordtypeIdChanged();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="Baseword"/> class.
        /// </summary>
        public Baseword()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets or sets the 'AbbrevationId' value.
        /// </summary>
        [DataMember()]
        [RoundtripOriginal()]
        public Nullable<int> AbbrevationId
        {
            get
            {
                return this._abbrevationId;
            }
            set
            {
                if ((this._abbrevationId != value))
                {
                    this.OnAbbrevationIdChanging(value);
                    this.RaiseDataMemberChanging("AbbrevationId");
                    this.ValidateProperty("AbbrevationId", value);
                    this._abbrevationId = value;
                    this.RaiseDataMemberChanged("AbbrevationId");
                    this.OnAbbrevationIdChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Comment' value.
        /// </summary>
        [DataMember()]
        public string Comment
        {
            get
            {
                return this._comment;
            }
            set
            {
                if ((this._comment != value))
                {
                    this.OnCommentChanging(value);
                    this.RaiseDataMemberChanging("Comment");
                    this.ValidateProperty("Comment", value);
                    this._comment = value;
                    this.RaiseDataMemberChanged("Comment");
                    this.OnCommentChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Id' value.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [DataMember()]
        [Editable(false, AllowInitialValue=true)]
        [Key()]
        [RoundtripOriginal()]
        public int Id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this.OnIdChanging(value);
                    this.ValidateProperty("Id", value);
                    this._id = value;
                    this.RaisePropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'IsLocked' value.
        /// </summary>
        [DataMember()]
        public Nullable<bool> IsLocked
        {
            get
            {
                return this._isLocked;
            }
            set
            {
                if ((this._isLocked != value))
                {
                    this.OnIsLockedChanging(value);
                    this.RaiseDataMemberChanging("IsLocked");
                    this.ValidateProperty("IsLocked", value);
                    this._isLocked = value;
                    this.RaiseDataMemberChanged("IsLocked");
                    this.OnIsLockedChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'LanguageId' value.
        /// </summary>
        [DataMember()]
        [RoundtripOriginal()]
        public int LanguageId
        {
            get
            {
                return this._languageId;
            }
            set
            {
                if ((this._languageId != value))
                {
                    this.OnLanguageIdChanging(value);
                    this.RaiseDataMemberChanging("LanguageId");
                    this.ValidateProperty("LanguageId", value);
                    this._languageId = value;
                    this.RaiseDataMemberChanged("LanguageId");
                    this.OnLanguageIdChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'ReferenceNumber' value.
        /// </summary>
        [DataMember()]
        public long ReferenceNumber
        {
            get
            {
                return this._referenceNumber;
            }
            set
            {
                if ((this._referenceNumber != value))
                {
                    this.OnReferenceNumberChanging(value);
                    this.RaiseDataMemberChanging("ReferenceNumber");
                    this.ValidateProperty("ReferenceNumber", value);
                    this._referenceNumber = value;
                    this.RaiseDataMemberChanged("ReferenceNumber");
                    this.OnReferenceNumberChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Status' value.
        /// </summary>
        [DataMember()]
        public Nullable<int> Status
        {
            get
            {
                return this._status;
            }
            set
            {
                if ((this._status != value))
                {
                    this.OnStatusChanging(value);
                    this.RaiseDataMemberChanging("Status");
                    this.ValidateProperty("Status", value);
                    this._status = value;
                    this.RaiseDataMemberChanged("Status");
                    this.OnStatusChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Text' value.
        /// </summary>
        [DataMember()]
        [Required()]
        public string Text
        {
            get
            {
                return this._text;
            }
            set
            {
                if ((this._text != value))
                {
                    this.OnTextChanging(value);
                    this.RaiseDataMemberChanging("Text");
                    this.ValidateProperty("Text", value);
                    this._text = value;
                    this.RaiseDataMemberChanged("Text");
                    this.OnTextChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Value' value.
        /// </summary>
        [DataMember()]
        public Nullable<int> Value
        {
            get
            {
                return this._value;
            }
            set
            {
                if ((this._value != value))
                {
                    this.OnValueChanging(value);
                    this.RaiseDataMemberChanging("Value");
                    this.ValidateProperty("Value", value);
                    this._value = value;
                    this.RaiseDataMemberChanged("Value");
                    this.OnValueChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'WordtypeId' value.
        /// </summary>
        [DataMember()]
        [RoundtripOriginal()]
        public int WordtypeId
        {
            get
            {
                return this._wordtypeId;
            }
            set
            {
                if ((this._wordtypeId != value))
                {
                    this.OnWordtypeIdChanging(value);
                    this.RaiseDataMemberChanging("WordtypeId");
                    this.ValidateProperty("WordtypeId", value);
                    this._wordtypeId = value;
                    this.RaiseDataMemberChanged("WordtypeId");
                    this.OnWordtypeIdChanged();
                }
            }
        }
        
        /// <summary>
        /// Computes a value from the key fields that uniquely identifies this entity instance.
        /// </summary>
        /// <returns>An object instance that uniquely identifies this entity instance.</returns>
        public override object GetIdentity()
        {
            return this._id;
        }
    }
    
    /// <summary>
    /// The 'Language' entity class.
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/Models.EF")]
    public sealed partial class Language : Entity
    {
        
        private string _code;
        
        private string _cultureName;
        
        private string _englishName;
        
        private int _id;
        
        private Nullable<bool> _isInterface;
        
        private string _nativeName;
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        partial void OnCultureNameChanging(string value);
        partial void OnCultureNameChanged();
        partial void OnEnglishNameChanging(string value);
        partial void OnEnglishNameChanged();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnIsInterfaceChanging(Nullable<bool> value);
        partial void OnIsInterfaceChanged();
        partial void OnNativeNameChanging(string value);
        partial void OnNativeNameChanged();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="Language"/> class.
        /// </summary>
        public Language()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets or sets the 'Code' value.
        /// </summary>
        [DataMember()]
        public string Code
        {
            get
            {
                return this._code;
            }
            set
            {
                if ((this._code != value))
                {
                    this.OnCodeChanging(value);
                    this.RaiseDataMemberChanging("Code");
                    this.ValidateProperty("Code", value);
                    this._code = value;
                    this.RaiseDataMemberChanged("Code");
                    this.OnCodeChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'CultureName' value.
        /// </summary>
        [DataMember()]
        public string CultureName
        {
            get
            {
                return this._cultureName;
            }
            set
            {
                if ((this._cultureName != value))
                {
                    this.OnCultureNameChanging(value);
                    this.RaiseDataMemberChanging("CultureName");
                    this.ValidateProperty("CultureName", value);
                    this._cultureName = value;
                    this.RaiseDataMemberChanged("CultureName");
                    this.OnCultureNameChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'EnglishName' value.
        /// </summary>
        [DataMember()]
        public string EnglishName
        {
            get
            {
                return this._englishName;
            }
            set
            {
                if ((this._englishName != value))
                {
                    this.OnEnglishNameChanging(value);
                    this.RaiseDataMemberChanging("EnglishName");
                    this.ValidateProperty("EnglishName", value);
                    this._englishName = value;
                    this.RaiseDataMemberChanged("EnglishName");
                    this.OnEnglishNameChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Id' value.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [DataMember()]
        [Editable(false, AllowInitialValue=true)]
        [Key()]
        [RoundtripOriginal()]
        public int Id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this.OnIdChanging(value);
                    this.ValidateProperty("Id", value);
                    this._id = value;
                    this.RaisePropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'IsInterface' value.
        /// </summary>
        [DataMember()]
        public Nullable<bool> IsInterface
        {
            get
            {
                return this._isInterface;
            }
            set
            {
                if ((this._isInterface != value))
                {
                    this.OnIsInterfaceChanging(value);
                    this.RaiseDataMemberChanging("IsInterface");
                    this.ValidateProperty("IsInterface", value);
                    this._isInterface = value;
                    this.RaiseDataMemberChanged("IsInterface");
                    this.OnIsInterfaceChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'NativeName' value.
        /// </summary>
        [DataMember()]
        public string NativeName
        {
            get
            {
                return this._nativeName;
            }
            set
            {
                if ((this._nativeName != value))
                {
                    this.OnNativeNameChanging(value);
                    this.RaiseDataMemberChanging("NativeName");
                    this.ValidateProperty("NativeName", value);
                    this._nativeName = value;
                    this.RaiseDataMemberChanged("NativeName");
                    this.OnNativeNameChanged();
                }
            }
        }
        
        /// <summary>
        /// Computes a value from the key fields that uniquely identifies this entity instance.
        /// </summary>
        /// <returns>An object instance that uniquely identifies this entity instance.</returns>
        public override object GetIdentity()
        {
            return this._id;
        }
    }
    
    /// <summary>
    /// The 'Wordtype' entity class.
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/Models.EF")]
    public sealed partial class Wordtype : Entity
    {
        
        private int _id;
        
        private string _text;
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnTextChanging(string value);
        partial void OnTextChanged();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="Wordtype"/> class.
        /// </summary>
        public Wordtype()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets or sets the 'Id' value.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [DataMember()]
        [Editable(false, AllowInitialValue=true)]
        [Key()]
        [RoundtripOriginal()]
        public int Id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this.OnIdChanging(value);
                    this.ValidateProperty("Id", value);
                    this._id = value;
                    this.RaisePropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Text' value.
        /// </summary>
        [DataMember()]
        [Required()]
        public string Text
        {
            get
            {
                return this._text;
            }
            set
            {
                if ((this._text != value))
                {
                    this.OnTextChanging(value);
                    this.RaiseDataMemberChanging("Text");
                    this.ValidateProperty("Text", value);
                    this._text = value;
                    this.RaiseDataMemberChanged("Text");
                    this.OnTextChanged();
                }
            }
        }
        
        /// <summary>
        /// Computes a value from the key fields that uniquely identifies this entity instance.
        /// </summary>
        /// <returns>An object instance that uniquely identifies this entity instance.</returns>
        public override object GetIdentity()
        {
            return this._id;
        }
    }
}
namespace Views.SL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    
    
    /// <summary>
    /// Context for the RIA application.
    /// </summary>
    /// <remarks>
    /// This context extends the base to make application services and types available
    /// for consumption from code and xaml.
    /// </remarks>
    public sealed partial class WebContext : WebContextBase
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the WebContext class.
        /// </summary>
        public WebContext()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets the context that is registered as a lifetime object with the current application.
        /// </summary>
        /// <exception cref="InvalidOperationException"> is thrown if there is no current application,
        /// no contexts have been added, or more than one context has been added.
        /// </exception>
        /// <seealso cref="System.Windows.Application.ApplicationLifetimeObjects"/>
        public new static WebContext Current
        {
            get
            {
                return ((WebContext)(WebContextBase.Current));
            }
        }
    }
}
namespace Views.SL.Web.xLinguaService
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.ServiceModel;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    using System.ServiceModel.Web;
    using Models.EF;
    
    
    /// <summary>
    /// The DomainContext corresponding to the 'BasewordContext' DomainService.
    /// </summary>
    public sealed partial class BasewordContext : DomainContext
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="BasewordContext"/> class.
        /// </summary>
        public BasewordContext() : 
                this(new WebDomainClient<IBasewordContextContract>(new Uri("Views-SL-Web-xLinguaService-BasewordContext.svc", UriKind.Relative)))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="BasewordContext"/> class with the specified service URI.
        /// </summary>
        /// <param name="serviceUri">The BasewordContext service URI.</param>
        public BasewordContext(Uri serviceUri) : 
                this(new WebDomainClient<IBasewordContextContract>(serviceUri))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="BasewordContext"/> class with the specified <paramref name="domainClient"/>.
        /// </summary>
        /// <param name="domainClient">The DomainClient instance to use for this DomainContext.</param>
        public BasewordContext(DomainClient domainClient) : 
                base(domainClient)
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets the set of <see cref="Baseword"/> entity instances that have been loaded into this <see cref="BasewordContext"/> instance.
        /// </summary>
        public EntitySet<Baseword> Basewords
        {
            get
            {
                return base.EntityContainer.GetEntitySet<Baseword>();
            }
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="Baseword"/> entity instances using the 'GetBasewordByText' query.
        /// </summary>
        /// <param name="text">The value for the 'text' parameter of the query.</param>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="Baseword"/> entity instances.</returns>
        public EntityQuery<Baseword> GetBasewordByTextQuery(string text)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("text", text);
            this.ValidateMethod("GetBasewordByTextQuery", parameters);
            return base.CreateQuery<Baseword>("GetBasewordByText", parameters, false, true);
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="Baseword"/> entity instances using the 'GetBasewords' query.
        /// </summary>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="Baseword"/> entity instances.</returns>
        public EntityQuery<Baseword> GetBasewordsQuery()
        {
            this.ValidateMethod("GetBasewordsQuery", null);
            return base.CreateQuery<Baseword>("GetBasewords", null, false, true);
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="Baseword"/> entity instances using the 'GetBasewordsByLanguageIdAndWordtypeId' query.
        /// </summary>
        /// <param name="languageId">The value for the 'languageId' parameter of the query.</param>
        /// <param name="wordtypeId">The value for the 'wordtypeId' parameter of the query.</param>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="Baseword"/> entity instances.</returns>
        public EntityQuery<Baseword> GetBasewordsByLanguageIdAndWordtypeIdQuery(int languageId, int wordtypeId)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("languageId", languageId);
            parameters.Add("wordtypeId", wordtypeId);
            this.ValidateMethod("GetBasewordsByLanguageIdAndWordtypeIdQuery", parameters);
            return base.CreateQuery<Baseword>("GetBasewordsByLanguageIdAndWordtypeId", parameters, false, true);
        }
        
        /// <summary>
        /// Creates a new EntityContainer for this DomainContext's EntitySets.
        /// </summary>
        /// <returns>A new container instance.</returns>
        protected override EntityContainer CreateEntityContainer()
        {
            return new BasewordContextEntityContainer();
        }
        
        /// <summary>
        /// Service contract for the 'BasewordContext' DomainService.
        /// </summary>
        [ServiceContract()]
        public interface IBasewordContextContract
        {
            
            /// <summary>
            /// Asynchronously invokes the 'GetBasewordByText' operation.
            /// </summary>
            /// <param name="text">The value for the 'text' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/BasewordContext/GetBasewordByTextDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/BasewordContext/GetBasewordByText", ReplyAction="http://tempuri.org/BasewordContext/GetBasewordByTextResponse")]
            [WebGet()]
            IAsyncResult BeginGetBasewordByText(string text, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetBasewordByText'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetBasewordByText'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetBasewordByText' operation.</returns>
            QueryResult<Baseword> EndGetBasewordByText(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetBasewords' operation.
            /// </summary>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/BasewordContext/GetBasewordsDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/BasewordContext/GetBasewords", ReplyAction="http://tempuri.org/BasewordContext/GetBasewordsResponse")]
            [WebGet()]
            IAsyncResult BeginGetBasewords(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetBasewords'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetBasewords'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetBasewords' operation.</returns>
            QueryResult<Baseword> EndGetBasewords(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetBasewordsByLanguageIdAndWordtypeId' operation.
            /// </summary>
            /// <param name="languageId">The value for the 'languageId' parameter of this action.</param>
            /// <param name="wordtypeId">The value for the 'wordtypeId' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/BasewordContext/GetBasewordsByLanguageIdAndWordtypeIdDomainSer" +
                "viceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/BasewordContext/GetBasewordsByLanguageIdAndWordtypeId", ReplyAction="http://tempuri.org/BasewordContext/GetBasewordsByLanguageIdAndWordtypeIdResponse")]
            [WebGet()]
            IAsyncResult BeginGetBasewordsByLanguageIdAndWordtypeId(int languageId, int wordtypeId, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetBasewordsByLanguageIdAndWordtypeId'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetBasewordsByLanguageIdAndWordtypeId'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetBasewordsByLanguageIdAndWordtypeId' operation.</returns>
            QueryResult<Baseword> EndGetBasewordsByLanguageIdAndWordtypeId(IAsyncResult result);
        }
        
        internal sealed class BasewordContextEntityContainer : EntityContainer
        {
            
            public BasewordContextEntityContainer()
            {
                this.CreateEntitySet<Baseword>(EntitySetOperations.None);
            }
        }
    }
    
    /// <summary>
    /// The DomainContext corresponding to the 'LanguageContext' DomainService.
    /// </summary>
    public sealed partial class LanguageContext : DomainContext
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="LanguageContext"/> class.
        /// </summary>
        public LanguageContext() : 
                this(new WebDomainClient<ILanguageContextContract>(new Uri("Views-SL-Web-xLinguaService-LanguageContext.svc", UriKind.Relative)))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="LanguageContext"/> class with the specified service URI.
        /// </summary>
        /// <param name="serviceUri">The LanguageContext service URI.</param>
        public LanguageContext(Uri serviceUri) : 
                this(new WebDomainClient<ILanguageContextContract>(serviceUri))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="LanguageContext"/> class with the specified <paramref name="domainClient"/>.
        /// </summary>
        /// <param name="domainClient">The DomainClient instance to use for this DomainContext.</param>
        public LanguageContext(DomainClient domainClient) : 
                base(domainClient)
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets the set of <see cref="Language"/> entity instances that have been loaded into this <see cref="LanguageContext"/> instance.
        /// </summary>
        public EntitySet<Language> Languages
        {
            get
            {
                return base.EntityContainer.GetEntitySet<Language>();
            }
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="Language"/> entity instances using the 'GetLanguageById' query.
        /// </summary>
        /// <param name="id">The value for the 'id' parameter of the query.</param>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="Language"/> entity instances.</returns>
        public EntityQuery<Language> GetLanguageByIdQuery(int id)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("id", id);
            this.ValidateMethod("GetLanguageByIdQuery", parameters);
            return base.CreateQuery<Language>("GetLanguageById", parameters, false, false);
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="Language"/> entity instances using the 'GetLanguages' query.
        /// </summary>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="Language"/> entity instances.</returns>
        public EntityQuery<Language> GetLanguagesQuery()
        {
            this.ValidateMethod("GetLanguagesQuery", null);
            return base.CreateQuery<Language>("GetLanguages", null, false, true);
        }
        
        /// <summary>
        /// Creates a new EntityContainer for this DomainContext's EntitySets.
        /// </summary>
        /// <returns>A new container instance.</returns>
        protected override EntityContainer CreateEntityContainer()
        {
            return new LanguageContextEntityContainer();
        }
        
        /// <summary>
        /// Service contract for the 'LanguageContext' DomainService.
        /// </summary>
        [ServiceContract()]
        public interface ILanguageContextContract
        {
            
            /// <summary>
            /// Asynchronously invokes the 'GetLanguageById' operation.
            /// </summary>
            /// <param name="id">The value for the 'id' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/LanguageContext/GetLanguageByIdDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/LanguageContext/GetLanguageById", ReplyAction="http://tempuri.org/LanguageContext/GetLanguageByIdResponse")]
            [WebGet()]
            IAsyncResult BeginGetLanguageById(int id, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetLanguageById'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetLanguageById'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetLanguageById' operation.</returns>
            QueryResult<Language> EndGetLanguageById(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetLanguages' operation.
            /// </summary>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/LanguageContext/GetLanguagesDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/LanguageContext/GetLanguages", ReplyAction="http://tempuri.org/LanguageContext/GetLanguagesResponse")]
            [WebGet()]
            IAsyncResult BeginGetLanguages(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetLanguages'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetLanguages'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetLanguages' operation.</returns>
            QueryResult<Language> EndGetLanguages(IAsyncResult result);
        }
        
        internal sealed class LanguageContextEntityContainer : EntityContainer
        {
            
            public LanguageContextEntityContainer()
            {
                this.CreateEntitySet<Language>(EntitySetOperations.None);
            }
        }
    }
    
    /// <summary>
    /// The DomainContext corresponding to the 'WordtypeContext' DomainService.
    /// </summary>
    public sealed partial class WordtypeContext : DomainContext
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="WordtypeContext"/> class.
        /// </summary>
        public WordtypeContext() : 
                this(new WebDomainClient<IWordtypeContextContract>(new Uri("Views-SL-Web-xLinguaService-WordtypeContext.svc", UriKind.Relative)))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="WordtypeContext"/> class with the specified service URI.
        /// </summary>
        /// <param name="serviceUri">The WordtypeContext service URI.</param>
        public WordtypeContext(Uri serviceUri) : 
                this(new WebDomainClient<IWordtypeContextContract>(serviceUri))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="WordtypeContext"/> class with the specified <paramref name="domainClient"/>.
        /// </summary>
        /// <param name="domainClient">The DomainClient instance to use for this DomainContext.</param>
        public WordtypeContext(DomainClient domainClient) : 
                base(domainClient)
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets the set of <see cref="Wordtype"/> entity instances that have been loaded into this <see cref="WordtypeContext"/> instance.
        /// </summary>
        public EntitySet<Wordtype> Wordtypes
        {
            get
            {
                return base.EntityContainer.GetEntitySet<Wordtype>();
            }
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="Wordtype"/> entity instances using the 'GetWordtypes' query.
        /// </summary>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="Wordtype"/> entity instances.</returns>
        public EntityQuery<Wordtype> GetWordtypesQuery()
        {
            this.ValidateMethod("GetWordtypesQuery", null);
            return base.CreateQuery<Wordtype>("GetWordtypes", null, false, true);
        }
        
        /// <summary>
        /// Creates a new EntityContainer for this DomainContext's EntitySets.
        /// </summary>
        /// <returns>A new container instance.</returns>
        protected override EntityContainer CreateEntityContainer()
        {
            return new WordtypeContextEntityContainer();
        }
        
        /// <summary>
        /// Service contract for the 'WordtypeContext' DomainService.
        /// </summary>
        [ServiceContract()]
        public interface IWordtypeContextContract
        {
            
            /// <summary>
            /// Asynchronously invokes the 'GetWordtypes' operation.
            /// </summary>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/WordtypeContext/GetWordtypesDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/WordtypeContext/GetWordtypes", ReplyAction="http://tempuri.org/WordtypeContext/GetWordtypesResponse")]
            [WebGet()]
            IAsyncResult BeginGetWordtypes(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetWordtypes'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetWordtypes'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetWordtypes' operation.</returns>
            QueryResult<Wordtype> EndGetWordtypes(IAsyncResult result);
        }
        
        internal sealed class WordtypeContextEntityContainer : EntityContainer
        {
            
            public WordtypeContextEntityContainer()
            {
                this.CreateEntitySet<Wordtype>(EntitySetOperations.None);
            }
        }
    }
}
