//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Views.SL.ModelService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasewordDto", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class BasewordDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CommentField;
        
        private int IdField;
        
        private bool IsLockedField;
        
        private Views.SL.ModelService.LanguageDto LanguageField;
        
        private string TextField;
        
        private Views.SL.ModelService.WordtypeDto WordtypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLocked {
            get {
                return this.IsLockedField;
            }
            set {
                if ((this.IsLockedField.Equals(value) != true)) {
                    this.IsLockedField = value;
                    this.RaisePropertyChanged("IsLocked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Views.SL.ModelService.LanguageDto Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Views.SL.ModelService.WordtypeDto Wordtype {
            get {
                return this.WordtypeField;
            }
            set {
                if ((object.ReferenceEquals(this.WordtypeField, value) != true)) {
                    this.WordtypeField = value;
                    this.RaisePropertyChanged("Wordtype");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LanguageDto", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class LanguageDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WordtypeDto", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class WordtypeDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ModelService.IModelService")]
    public interface IModelService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IModelService/GetBasewordsByText", ReplyAction="http://tempuri.org/IModelService/GetBasewordsByTextResponse")]
        System.IAsyncResult BeginGetBasewordsByText(string text, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.BasewordDto> EndGetBasewordsByText(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IModelService/GetSupportedLanguages", ReplyAction="http://tempuri.org/IModelService/GetSupportedLanguagesResponse")]
        System.IAsyncResult BeginGetSupportedLanguages(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.LanguageDto> EndGetSupportedLanguages(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IModelService/GetWordtypes", ReplyAction="http://tempuri.org/IModelService/GetWordtypesResponse")]
        System.IAsyncResult BeginGetWordtypes(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.WordtypeDto> EndGetWordtypes(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IModelService/UpdateBaseword", ReplyAction="http://tempuri.org/IModelService/UpdateBasewordResponse")]
        System.IAsyncResult BeginUpdateBaseword(Views.SL.ModelService.BasewordDto baseword, System.AsyncCallback callback, object asyncState);
        
        bool EndUpdateBaseword(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IModelServiceChannel : Views.SL.ModelService.IModelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetBasewordsByTextCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetBasewordsByTextCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.BasewordDto> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.BasewordDto>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSupportedLanguagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSupportedLanguagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.LanguageDto> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.LanguageDto>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWordtypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWordtypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.WordtypeDto> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.WordtypeDto>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateBasewordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateBasewordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModelServiceClient : System.ServiceModel.ClientBase<Views.SL.ModelService.IModelService>, Views.SL.ModelService.IModelService {
        
        private BeginOperationDelegate onBeginGetBasewordsByTextDelegate;
        
        private EndOperationDelegate onEndGetBasewordsByTextDelegate;
        
        private System.Threading.SendOrPostCallback onGetBasewordsByTextCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSupportedLanguagesDelegate;
        
        private EndOperationDelegate onEndGetSupportedLanguagesDelegate;
        
        private System.Threading.SendOrPostCallback onGetSupportedLanguagesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetWordtypesDelegate;
        
        private EndOperationDelegate onEndGetWordtypesDelegate;
        
        private System.Threading.SendOrPostCallback onGetWordtypesCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateBasewordDelegate;
        
        private EndOperationDelegate onEndUpdateBasewordDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateBasewordCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ModelServiceClient() {
        }
        
        public ModelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetBasewordsByTextCompletedEventArgs> GetBasewordsByTextCompleted;
        
        public event System.EventHandler<GetSupportedLanguagesCompletedEventArgs> GetSupportedLanguagesCompleted;
        
        public event System.EventHandler<GetWordtypesCompletedEventArgs> GetWordtypesCompleted;
        
        public event System.EventHandler<UpdateBasewordCompletedEventArgs> UpdateBasewordCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Views.SL.ModelService.IModelService.BeginGetBasewordsByText(string text, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetBasewordsByText(text, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.BasewordDto> Views.SL.ModelService.IModelService.EndGetBasewordsByText(System.IAsyncResult result) {
            return base.Channel.EndGetBasewordsByText(result);
        }
        
        private System.IAsyncResult OnBeginGetBasewordsByText(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string text = ((string)(inValues[0]));
            return ((Views.SL.ModelService.IModelService)(this)).BeginGetBasewordsByText(text, callback, asyncState);
        }
        
        private object[] OnEndGetBasewordsByText(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.BasewordDto> retVal = ((Views.SL.ModelService.IModelService)(this)).EndGetBasewordsByText(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetBasewordsByTextCompleted(object state) {
            if ((this.GetBasewordsByTextCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetBasewordsByTextCompleted(this, new GetBasewordsByTextCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetBasewordsByTextAsync(string text) {
            this.GetBasewordsByTextAsync(text, null);
        }
        
        public void GetBasewordsByTextAsync(string text, object userState) {
            if ((this.onBeginGetBasewordsByTextDelegate == null)) {
                this.onBeginGetBasewordsByTextDelegate = new BeginOperationDelegate(this.OnBeginGetBasewordsByText);
            }
            if ((this.onEndGetBasewordsByTextDelegate == null)) {
                this.onEndGetBasewordsByTextDelegate = new EndOperationDelegate(this.OnEndGetBasewordsByText);
            }
            if ((this.onGetBasewordsByTextCompletedDelegate == null)) {
                this.onGetBasewordsByTextCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetBasewordsByTextCompleted);
            }
            base.InvokeAsync(this.onBeginGetBasewordsByTextDelegate, new object[] {
                        text}, this.onEndGetBasewordsByTextDelegate, this.onGetBasewordsByTextCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Views.SL.ModelService.IModelService.BeginGetSupportedLanguages(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSupportedLanguages(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.LanguageDto> Views.SL.ModelService.IModelService.EndGetSupportedLanguages(System.IAsyncResult result) {
            return base.Channel.EndGetSupportedLanguages(result);
        }
        
        private System.IAsyncResult OnBeginGetSupportedLanguages(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Views.SL.ModelService.IModelService)(this)).BeginGetSupportedLanguages(callback, asyncState);
        }
        
        private object[] OnEndGetSupportedLanguages(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.LanguageDto> retVal = ((Views.SL.ModelService.IModelService)(this)).EndGetSupportedLanguages(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSupportedLanguagesCompleted(object state) {
            if ((this.GetSupportedLanguagesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSupportedLanguagesCompleted(this, new GetSupportedLanguagesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSupportedLanguagesAsync() {
            this.GetSupportedLanguagesAsync(null);
        }
        
        public void GetSupportedLanguagesAsync(object userState) {
            if ((this.onBeginGetSupportedLanguagesDelegate == null)) {
                this.onBeginGetSupportedLanguagesDelegate = new BeginOperationDelegate(this.OnBeginGetSupportedLanguages);
            }
            if ((this.onEndGetSupportedLanguagesDelegate == null)) {
                this.onEndGetSupportedLanguagesDelegate = new EndOperationDelegate(this.OnEndGetSupportedLanguages);
            }
            if ((this.onGetSupportedLanguagesCompletedDelegate == null)) {
                this.onGetSupportedLanguagesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSupportedLanguagesCompleted);
            }
            base.InvokeAsync(this.onBeginGetSupportedLanguagesDelegate, null, this.onEndGetSupportedLanguagesDelegate, this.onGetSupportedLanguagesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Views.SL.ModelService.IModelService.BeginGetWordtypes(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWordtypes(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.WordtypeDto> Views.SL.ModelService.IModelService.EndGetWordtypes(System.IAsyncResult result) {
            return base.Channel.EndGetWordtypes(result);
        }
        
        private System.IAsyncResult OnBeginGetWordtypes(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Views.SL.ModelService.IModelService)(this)).BeginGetWordtypes(callback, asyncState);
        }
        
        private object[] OnEndGetWordtypes(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.WordtypeDto> retVal = ((Views.SL.ModelService.IModelService)(this)).EndGetWordtypes(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWordtypesCompleted(object state) {
            if ((this.GetWordtypesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWordtypesCompleted(this, new GetWordtypesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWordtypesAsync() {
            this.GetWordtypesAsync(null);
        }
        
        public void GetWordtypesAsync(object userState) {
            if ((this.onBeginGetWordtypesDelegate == null)) {
                this.onBeginGetWordtypesDelegate = new BeginOperationDelegate(this.OnBeginGetWordtypes);
            }
            if ((this.onEndGetWordtypesDelegate == null)) {
                this.onEndGetWordtypesDelegate = new EndOperationDelegate(this.OnEndGetWordtypes);
            }
            if ((this.onGetWordtypesCompletedDelegate == null)) {
                this.onGetWordtypesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWordtypesCompleted);
            }
            base.InvokeAsync(this.onBeginGetWordtypesDelegate, null, this.onEndGetWordtypesDelegate, this.onGetWordtypesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Views.SL.ModelService.IModelService.BeginUpdateBaseword(Views.SL.ModelService.BasewordDto baseword, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateBaseword(baseword, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool Views.SL.ModelService.IModelService.EndUpdateBaseword(System.IAsyncResult result) {
            return base.Channel.EndUpdateBaseword(result);
        }
        
        private System.IAsyncResult OnBeginUpdateBaseword(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Views.SL.ModelService.BasewordDto baseword = ((Views.SL.ModelService.BasewordDto)(inValues[0]));
            return ((Views.SL.ModelService.IModelService)(this)).BeginUpdateBaseword(baseword, callback, asyncState);
        }
        
        private object[] OnEndUpdateBaseword(System.IAsyncResult result) {
            bool retVal = ((Views.SL.ModelService.IModelService)(this)).EndUpdateBaseword(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateBasewordCompleted(object state) {
            if ((this.UpdateBasewordCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateBasewordCompleted(this, new UpdateBasewordCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateBasewordAsync(Views.SL.ModelService.BasewordDto baseword) {
            this.UpdateBasewordAsync(baseword, null);
        }
        
        public void UpdateBasewordAsync(Views.SL.ModelService.BasewordDto baseword, object userState) {
            if ((this.onBeginUpdateBasewordDelegate == null)) {
                this.onBeginUpdateBasewordDelegate = new BeginOperationDelegate(this.OnBeginUpdateBaseword);
            }
            if ((this.onEndUpdateBasewordDelegate == null)) {
                this.onEndUpdateBasewordDelegate = new EndOperationDelegate(this.OnEndUpdateBaseword);
            }
            if ((this.onUpdateBasewordCompletedDelegate == null)) {
                this.onUpdateBasewordCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateBasewordCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateBasewordDelegate, new object[] {
                        baseword}, this.onEndUpdateBasewordDelegate, this.onUpdateBasewordCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Views.SL.ModelService.IModelService CreateChannel() {
            return new ModelServiceClientChannel(this);
        }
        
        private class ModelServiceClientChannel : ChannelBase<Views.SL.ModelService.IModelService>, Views.SL.ModelService.IModelService {
            
            public ModelServiceClientChannel(System.ServiceModel.ClientBase<Views.SL.ModelService.IModelService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetBasewordsByText(string text, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = text;
                System.IAsyncResult _result = base.BeginInvoke("GetBasewordsByText", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.BasewordDto> EndGetBasewordsByText(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.BasewordDto> _result = ((System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.BasewordDto>)(base.EndInvoke("GetBasewordsByText", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetSupportedLanguages(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetSupportedLanguages", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.LanguageDto> EndGetSupportedLanguages(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.LanguageDto> _result = ((System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.LanguageDto>)(base.EndInvoke("GetSupportedLanguages", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetWordtypes(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetWordtypes", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.WordtypeDto> EndGetWordtypes(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.WordtypeDto> _result = ((System.Collections.ObjectModel.ObservableCollection<Views.SL.ModelService.WordtypeDto>)(base.EndInvoke("GetWordtypes", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateBaseword(Views.SL.ModelService.BasewordDto baseword, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = baseword;
                System.IAsyncResult _result = base.BeginInvoke("UpdateBaseword", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndUpdateBaseword(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("UpdateBaseword", _args, result)));
                return _result;
            }
        }
    }
}
